EvaluacionWebClient/Controllers/ClientsController.cs
using EvaluacionWeb.Models;
using EvaluacionWebMVC.DefaultSettings;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace EvaluacionWebClient.Controllers
{
    public class ClientsController : Controller
    {
        // GET: Clients
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetClients()
        {
            IEnumerable<Cliente> Clients = new List<Cliente>();
            HttpResponseMessage Response = WebServerInformation.HttpClient.GetAsync("Clientes").Result;
            Clients = Response.Content.ReadAsAsync<IEnumerable<Cliente>>().Result;

            var draw = Request.Form.GetValues("draw").FirstOrDefault();
            var model = (Clients.ToList()
                        .Select(x => new
                        {
                            idCliente = x.IdCliente,
                            idTipoPersona = x.IdTipoPersona,
                            razonSocial = x.RazonSocial,
                            nombreComercial = x.NombreComercial,
                            rfc = x.RFC,
                            curp = x.CURP,
                            direccion = x.Direccion
                        })).ToList();

            return Json(new
            {
                draw = draw,
                recordsFiltered = model.Count,
                recordsTotal = model.Count,
                data = model
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SaveClient(Cliente Cliente)
        {
            Cliente NuevoCliente = new Cliente();

            if (Cliente.Contactos == null)
            {
                Cliente.Contactos = new List<Contacto>();
            }

            if (Cliente.TipoPersona == null)
            {
                Cliente.TipoPersona = new TipoPersona();
            }

            if (Cliente.IdCliente > 0)
            {
                HttpResponseMessage Response = WebServerInformation.HttpClient.PutAsJsonAsync("Clientes/" + Cliente.IdCliente.ToString(), Cliente).Result;
                NuevoCliente = Response.Content.ReadAsAsync<Cliente>().Result;
            }
            else
            {
                HttpResponseMessage Response = WebServerInformation.HttpClient.PostAsJsonAsync("Clientes", Cliente).Result;
                NuevoCliente = Response.Content.ReadAsAsync<Cliente>().Result;
            }           

            if (!(NuevoCliente.IdCliente > 0))
            {
                return Json(new { error = true, message = "No se han podido guardar los datos del cliente." });
            }

            return Json(new { error = false, message = "Cliente guardado satisfactoriamente!" });

        }

        public ActionResult GetSingleClient(int? clientId)
        {
            Cliente ClienteConsultado = new Cliente();
            HttpResponseMessage Response = WebServerInformation.HttpClient.GetAsync("Clientes/" + clientId.ToString()).Result;
            ClienteConsultado = Response.Content.ReadAsAsync<Cliente>().Result;

            return Json(new { result = ClienteConsultado }, JsonRequestBehavior.AllowGet);

        }

        public ActionResult GetPersonTypes()
        {
            IEnumerable<TipoPersona> PersonTypes = new List<TipoPersona>();
            PersonTypes = WebServerInformation.PersonTypesForLists;

            var model = (PersonTypes.ToList()
                        .Select(x => new
                        {
                            idTipoPersona = x.IdTipoPersona,
                            descripcion = x.Descripcion
                        })).ToList();

            return Json(model, JsonRequestBehavior.AllowGet);

        }

        public ActionResult GetJobs()
        {
            IEnumerable<PuestoTrabajo> Jobs = new List<PuestoTrabajo>();
            Jobs = WebServerInformation.JobsForLists;

            var model = (Jobs.ToList()
                        .Select(x => new
                        {
                            idPuestoTrabajo = x.IdPuestoTrabajo,
                            descripcion = x.Descripcion
                        })).ToList();

            return Json(model, JsonRequestBehavior.AllowGet);

        }

        // GET: Clients/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Clients/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Clients/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Clients/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Clients/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Clients/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

EvaluacionWebClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - Evaluacion</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Evaluacion Web", "Index", "Clients", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Evaluacion</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @*<script type="text/javascript" src=" https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css">*@
    @Scripts.Render("~/bundles/bootstrap")
    @*<link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.5/css/bootstrap.css" rel="stylesheet" />
    <link href="http://www.genecopoeia.com/includes/DataTables/media/css/dataTables.bootstrap4.css" rel="stylesheet" />*@
    <link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap4.min.css" rel="stylesheet" />
    @RenderSection("scripts", required: false)
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap4.min.js"></script>
</body>
</html>